import { Lead } from "@/lib/types";

export const leads: Lead[] = [
  {
    id: "lead_001",
    name: "Barry O'Sullivan",
    email: "barry@revscale.io",
    title: "Head of Sales",
    company: "RevScale",
    lifecycleStage: "lead",
    lastContactedDays: 72,
    companyData: {
      industry: "B2B SaaS",
      employees: 120,
      location: "Dublin, Ireland",
      signal: "Hiring 5 SDRs and 2 AEs",
      domain: "revscale.io",
    },
    activities: [
      { type: "call", note: "Discussed scaling outbound and rep productivity concerns.", daysAgo: 75 },
      { type: "email_open", note: "Opened pricing follow-up email.", daysAgo: 10 },
      { type: "note", note: "Mentioned team was stretched and coverage was inconsistent.", daysAgo: 74 },
    ],
  },
  {
    id: "lead_002",
    name: "Anna Meyer",
    email: "anna@revscale.io",
    title: "VP Revenue Operations",
    company: "RevScale",
    lifecycleStage: "opportunity",
    lastContactedDays: 45,
    companyData: {
      industry: "B2B SaaS",
      employees: 120,
      location: "Berlin, Germany",
      signal: "Hiring SDRs and implementing a new CRM process",
      domain: "revscale.io",
    },
    activities: [
      { type: "webinar", note: "Attended webinar on pipeline coverage and reactivation.", daysAgo: 30 },
      { type: "email_click", note: "Clicked case study about dormant lead recovery.", daysAgo: 28 },
      { type: "note", note: "Interested in operational efficiency more than net-new tooling.", daysAgo: 44 },
    ],
  },
  {
    id: "lead_003",
    name: "James Wright",
    email: "james@logihub.com",
    title: "Director of Sales",
    company: "LogiHub",
    lifecycleStage: "lead",
    lastContactedDays: 91,
    companyData: {
      industry: "Logistics SaaS",
      employees: 280,
      location: "London, UK",
      signal: "Raised Series B 4 months ago",
      domain: "logihub.com",
    },
    activities: [
      { type: "meeting", note: "Initial discovery meeting. Strong fit but poor timing.", daysAgo: 102 },
      { type: "note", note: "Said they would revisit once new budget cycle opened.", daysAgo: 101 },
    ],
  },
  {
    id: "lead_004",
    name: "Sophie Laurent",
    email: "sophie@funnelpilot.ai",
    title: "Head of RevOps",
    company: "FunnelPilot",
    lifecycleStage: "stalled",
    lastContactedDays: 67,
    companyData: {
      industry: "B2B SaaS",
      employees: 85,
      location: "Paris, France",
      signal: "Hiring RevOps Analyst and SDR Manager",
      domain: "funnelpilot.ai",
    },
    activities: [
      { type: "call", note: "Wanted better prioritisation across stale pipeline.", daysAgo: 70 },
      { type: "email_open", note: "Opened follow-up email with use case summary.", daysAgo: 9 },
      { type: "note", note: "Mentioned CRM is full of old leads that no one touches.", daysAgo: 69 },
    ],
  },
  {
    id: "lead_005",
    name: "Liam Carter",
    email: "liam@crewstack.com",
    title: "Founder",
    company: "CrewStack",
    lifecycleStage: "lead",
    lastContactedDays: 58,
    companyData: {
      industry: "Maritime Workforce SaaS",
      employees: 60,
      location: "Amsterdam, Netherlands",
      signal: "Expanding go-to-market team after strong quarter",
      domain: "crewstack.com",
    },
    activities: [
      { type: "meeting", note: "Explored how to improve commercial efficiency with a small team.", daysAgo: 61 },
      { type: "note", note: "Founder was interested but wanted to revisit post-quarter.", daysAgo: 60 },
      { type: "email_open", note: "Opened recap email.", daysAgo: 14 },
    ],
  },
  {
    id: "lead_006",
    name: "Maria Jensen",
    email: "maria@adlift.io",
    title: "VP Marketing",
    company: "AdLift",
    lifecycleStage: "lead",
    lastContactedDays: 76,
    companyData: {
      industry: "Marketing Software",
      employees: 210,
      location: "Copenhagen, Denmark",
      signal: "Launching new product line",
      domain: "adlift.io",
    },
    activities: [
      { type: "webinar", note: "Attended webinar on improving conversion from existing demand.", daysAgo: 33 },
      { type: "email_click", note: "Clicked product overview for conversion optimisation.", daysAgo: 31 },
      { type: "note", note: "Interested in better downstream conversion, not just more leads.", daysAgo: 75 },
    ],
  },
  {
    id: "lead_007",
    name: "Tom Becker",
    email: "tom@opsmate.com",
    title: "Head of Sales",
    company: "OpsMate",
    lifecycleStage: "lead",
    lastContactedDays: 22,
    companyData: {
      industry: "Operations SaaS",
      employees: 150,
      location: "Munich, Germany",
      signal: "Expanding into UK market",
      domain: "opsmate.com",
    },
    activities: [
      { type: "call", note: "Recent discovery call.", daysAgo: 25 },
      { type: "note", note: "Wanted examples specific to scaling into new regions.", daysAgo: 24 },
    ],
  },
  {
    id: "lead_008",
    name: "Eleanor Shaw",
    email: "eleanor@signalpath.io",
    title: "Revenue Operations Director",
    company: "SignalPath",
    lifecycleStage: "stalled",
    lastContactedDays: 83,
    companyData: {
      industry: "B2B SaaS",
      employees: 340,
      location: "Manchester, UK",
      signal: "Reviewing sales process and funnel leakage",
      domain: "signalpath.io",
    },
    activities: [
      { type: "meeting", note: "Strong interest in identifying neglected warm pipeline.", daysAgo: 88 },
      { type: "email_open", note: "Opened follow-up twice.", daysAgo: 7 },
      { type: "note", note: "Said timing was bad due to quarter-end priorities.", daysAgo: 87 },
    ],
  },
];

export function getLeadById(id: string) {
  return leads.find((lead) => lead.id === id);
}
